### ISSUE TITLE
App fails to start

### ISSUE THREAD

**Issue by njohnson85** [grafana/tutorial-environment#14] opened 2022-02-09 00:00 UTC
When I run docker-compose up -d; most of the containers start except "tutorial-environment_app" and "grafana/tns-db:latest". In looking at the docker logs, the following errors are reported:

In the "app" the error is:

./app: 1: Syntax error: "(" unexpected

In the db container, the error is:

standard_init_linux.go:228: exec user process caused: exec format error

I am running this on a Raspberry PI with the 64 bit OS . 

Any ideas?

**Comment by njohnson85** [comment] 2022-02-09 03:36
I did confirm that all services start when running it on my macbook - so I am guessing it is a platform issue on the raspberry pi???

**Comment by DaZzLa09** [comment] 2022-04-21 14:49
I have the same issue. Also on Raspberry Pi 4. Did you managed to fix it?

**Comment by zuchka** [comment] 2022-05-19 22:00
the docker-compose works on my macbook M1 and ubuntu 20.04 vm. So maybe a Pi thing?

**Comment by zuchka** [comment] 2022-05-19 22:02
closing this as a duplicate of #5

**Closed by zuchka** 2022-05-19 22:02 UTC
